# Branch Protection Configuration
# This file documents the recommended branch protection rules
# These should be configured in GitHub repository settings

branch_protection_rules:
  main:
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build and Test (macos-latest)"
        - "Security Scan / Dependency Vulnerability Scan"
        - "Security Scan / Static Code Analysis"
        - "Security Scan / Secrets Detection"
        - "Performance Tests"
        - "SwiftLint"
    
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      require_last_push_approval: true
      restrictions:
        users: []
        teams: ["core-developers", "security-team"]
    
    restrictions:
      users: []
      teams: ["core-developers"]
    
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: true
    allow_auto_merge: false
    delete_branch_on_merge: true

  develop:
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build and Test (macos-latest)"
        - "SwiftLint"
        - "Unit Tests"
    
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: false
    allow_auto_merge: true
    delete_branch_on_merge: true

# Additional protection for release branches
  "release/*":
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build and Test (macos-latest)"
        - "Security Scan / Dependency Vulnerability Scan"
        - "Security Scan / Static Code Analysis"
        - "Performance Tests"
        - "Release Tests"
    
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: true

# Configuration Notes:
# 1. These rules should be applied via GitHub repository settings
# 2. Teams mentioned should be created in GitHub organization
# 3. CODEOWNERS file should be created to define code ownership
# 4. Status checks should match actual workflow job names