version: 2
updates:
  # Swift Package Manager
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@core-team"
    assignees:
      - "@GrandMasteriOSBuilder"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    
  # Ruby dependencies (Fastlane, gems)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@core-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 3
      
  # CocoaPods dependencies
  - package-ecosystem: "cocoapods"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@core-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 3
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@core-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 2