disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - missing_docs
  - closure_spacing
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - number_separator
  - prohibited_super_call
  - fatal_error_message

included:
  - AI-Mixtapes
  - Tests

excluded:
  - Pods
  - fastlane
  - .build
  - DerivedData
  - AI-Mixtapes.xcodeproj
  - AI_Mixtapes.xcdatamodeld

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - x
    - y

reporter: "xcode"
