name: AIMixtapes
options:
  bundleIdPrefix: com.aimimixtapes
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.0
    macOS: 12.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  AIMixtapes-iOS:
    build:
      targets:
        AIMixtapes: all
    run:
      config: Debug
      platform: iOS
      simulators:
        - name: "iPhone 14 Pro"
        - name: "iPad Pro (12.9-inch)"
      customSchemeCommands:
        preActions:
          - script: |
              defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
        postActions:
          - script: |
              osascript -e 'display notification "iOS Build Complete" with title "AIMixtapes"'
    test:
      config: Debug
      platform: iOS
      targets: 
        - AIMixtapesTests
      gatherCoverageData: true
      
  AIMixtapes-macOS:
    build:
      targets:
        AIMixtapes: all
    run:
      config: Debug
      platform: macOS
    test:
      config: Debug
      platform: macOS
      targets:
        - AIMixtapesTests
      gatherCoverageData: true

packages:
  AudioKit:
    url: https://github.com/AudioKit/AudioKit
    from: "5.6.0"
  SoundpipeAudioKit:
    url: https://github.com/AudioKit/SoundpipeAudioKit
    from: "5.6.0"

settings:
  base:
    DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: NO
    SUPPORTED_PLATFORMS: macosx
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    SWIFT_STRICT_CONCURRENCY: complete
    TARGETED_DEVICE_FAMILY: mac
    CODE_SIGN_ENTITLEMENTS: AI-Mixtapes.entitlements
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
    SDKROOT: macosx
    COMBINE_HIDPI_IMAGES: YES
    ENABLE_HARDENED_RUNTIME: YES
    VALID_ARCHS: "x86_64 arm64"
    INTENT_DEFINITION_CODEGEN_MODE: none
    INTENT_DEFINITION_TARGET: AI-Mixtapes

configs:
  Debug:
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS:
        - DEBUG
        - ENABLE_METAL_ACCELERATION
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      ENABLE_TESTABILITY: YES
    xcconfig: Debug.xcconfig
  Release:
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule
      ENABLE_NS_ASSERTIONS: NO
    xcconfig: Release.xcconfig

targets:
  AI-Mixtapes:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/App
      - path: Sources/AIMixtapes
        excludes:
          - "Services/**"
          - "Models/**"
          - "ViewModels/**"
          - "Views/**"
      - path: Models
      - path: Services
      - path: ViewModels
      - path: Views
    resources:
      - path: Sources/App/Resources/Assets.xcassets
      - path: Intents.intentdefinition
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swanand.aimixtapes
        INFOPLIST_FILE: Info.plist
        MARKETING_VERSION: 0.9.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
    dependencies:
      - package: AudioKit
      - package: SoundpipeAudioKit
    preBuildScripts:
      - name: SwiftFormat
        script: |
          if which swiftformat >/dev/null; then
            swiftformat .
          else
            echo "warning: SwiftFormat not installed"
          fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/formatted-files
        inputFiles:
          - $(SRCROOT)/Sources
          - $(SRCROOT)/Models
          - $(SRCROOT)/Services
          - $(SRCROOT)/ViewModels
          - $(SRCROOT)/Views
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint lint --strict
          else
            echo "warning: SwiftLint not installed"
          fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint.result
        inputFiles:
          - $(SRCROOT)/Sources
          - $(SRCROOT)/Models
          - $(SRCROOT)/Services
          - $(SRCROOT)/ViewModels
          - $(SRCROOT)/Views

  AI-MixtapesTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
        excludes:
          - "UITests/**"
          - "**/UITests/**"
    dependencies:
      - target: AI-Mixtapes
      - package: AudioKit
      - package: SoundpipeAudioKit
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/AI-Mixtapes.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/AI-Mixtapes
        ENABLE_TESTING: YES
        GENERATE_INFOPLIST_FILE: YES
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos macosx"

  AI-MixtapesUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Tests/UITests
    dependencies:
      - target: AI-Mixtapes
    settings:
      INFOPLIST_FILE: Tests/UITests/Info.plist
