name: AI-Mixtapes
options:
  bundleIdPrefix: com.swanand
  createIntermediateGroups: true
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  AI-Mixtapes:
    build:
      targets:
        AI-Mixtapes: any
    run:
      config: Debug

packages:
  AudioKit:
    url: https://github.com/AudioKit/AudioKit
    from: "5.6.0"
  SoundpipeAudioKit:
    url: https://github.com/AudioKit/SoundpipeAudioKit
    from: "5.6.0"
  Domain:
    path: Sources/Domain

settings:
  base:
    DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
    SWIFT_VERSION: "5.9"
    ENABLE_BITCODE: NO
    SUPPORTED_PLATFORMS: macosx iphoneos iphonesimulator
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_ENTITLEMENTS: AI-Mixtapes.entitlements

configs:
  Debug:
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS:
        - DEBUG
        - ENABLE_METAL_ACCELERATION
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      ENABLE_TESTABILITY: YES
    xcconfig: Debug.xcconfig
  Release:
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule
      ENABLE_NS_ASSERTIONS: NO
    xcconfig: Release.xcconfig

targets:
  AI-Mixtapes:
    type: application
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "15.0"
      macOS: "12.0"
    sources:
      - path: Sources
        excludes:
          - "Domain/**"
          - "Tests/**"
      - path: Models
      - path: Services
      - path: ViewModels
      - path: Views
      - path: Resources
      - path: Info.plist
    resources:
      - path: LaunchScreen.storyboard
      - path: Intents.intentdefinition
      - path: Sources/AIMixtapes/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swanand.aimixtapes
        INFOPLIST_FILE: Info.plist
        MARKETING_VERSION: 0.9.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
    dependencies:
      - package: AudioKit
      - package: SoundpipeAudioKit
      - package: Domain
    preBuildScripts:
      - name: SwiftFormat
        script: |
          if which swiftformat >/dev/null; then
            swiftformat .
          else
            echo "warning: SwiftFormat not installed"
          fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/formatted-files
        inputFiles:
          - $(SRCROOT)/Sources
          - $(SRCROOT)/Models
          - $(SRCROOT)/Services
          - $(SRCROOT)/ViewModels
          - $(SRCROOT)/Views
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            swiftlint lint --strict
          else
            echo "warning: SwiftLint not installed"
          fi
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint.result
        inputFiles:
          - $(SRCROOT)/Sources
          - $(SRCROOT)/Models
          - $(SRCROOT)/Services
          - $(SRCROOT)/ViewModels
          - $(SRCROOT)/Views

  AI-MixtapesTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
        excludes:
          - "UITests/**"
          - "**/UITests/**"
    dependencies:
      - target: AI-Mixtapes
      - package: AudioKit
      - package: SoundpipeAudioKit
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/AI-Mixtapes.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/AI-Mixtapes
        ENABLE_TESTING: YES
        GENERATE_INFOPLIST_FILE: YES
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos macosx"

  AI-MixtapesUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Tests/UITests
    dependencies:
      - target: AI-Mixtapes
    settings:
      INFOPLIST_FILE: Tests/UITests/Info.plist
