name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - GrandMasteriOSBuilder
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the contributing guidelines
          required: true
        - label: This issue is related to the AI-Mixtapes app functionality
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - AI Music Generation
        - Audio Processing
        - MusicKit Integration
        - User Interface
        - Performance
        - Data Management
        - Authentication
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (App crashes, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - iPhone 16 Pro Max
        - iPhone 16 Pro
        - iPhone 16 Plus
        - iPhone 16
        - iPhone 15 Pro Max
        - iPhone 15 Pro
        - iPhone 15 Plus
        - iPhone 15
        - iPhone 14 Pro Max
        - iPhone 14 Pro
        - iPhone 14 Plus
        - iPhone 14
        - iPhone 13 Pro Max
        - iPhone 13 Pro
        - iPhone 13
        - iPhone 13 mini
        - iPhone 12 Pro Max
        - iPhone 12 Pro
        - iPhone 12
        - iPhone 12 mini
        - iPad Pro
        - iPad Air
        - iPad
        - iPad mini
        - Other
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      description: What version of iOS are you running?
      placeholder: e.g., 17.2
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of AI-Mixtapes are you using?
      placeholder: e.g., 1.0.0 (Build 123)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: If applicable, add console logs or crash reports
      placeholder: Paste any relevant logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: ai-related
    attributes:
      label: AI-Specific Issues
      description: If this is related to AI functionality, please check all that apply
      options:
        - label: AI model inference issues
        - label: Music generation quality problems
        - label: Performance issues during AI processing
        - label: Memory issues with AI models
        - label: Audio analysis problems