name: Bug report
description: File a bug report to help us improve
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: 1) … 2) … 3) …
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: iOS version, device, Xcode version
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      placeholder: Attach relevant logs or screenshots
