default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    run_tests(
      project: "AI-Mixtapes.xcodeproj",
      scheme: "AI-Mixtapes",
      code_coverage: true,
      devices: ["iPhone 16 Pro"],
      clean: true
    )
  end

  desc "Build debug version"
  lane :build_debug do
    build_ios_app(
      project: "AI-Mixtapes.xcodeproj",
      scheme: "AI-Mixtapes",
      configuration: "Debug",
      clean: true,
      export_method: "development"
    )
  end

  desc "Build release version"
  lane :build_release do
    build_ios_app(
      project: "AI-Mixtapes.xcodeproj",
      scheme: "AI-Mixtapes",
      configuration: "Release",
      clean: true,
      export_method: "app-store"
    )
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      strict: true
    )
  end
end
