source "https://rubygems.org"

gem "fastlane", "~> 2.219.0"
gem "cocoapods", "~> 1.14.0"
gem "xcpretty", "~> 0.3.0"
gem "json", "~> 2.7.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
