name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode select (ensure default)
        run: |
          xcode-select -p
          xcodebuild -version

      - name: Swift build
        run: |
          swift --version
          swift build

      - name: Swift test
        run: swift test

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build iOS app (Simulator)
        run: |
          set -e
          xcodebuild -project Encorely.xcodeproj -scheme Encorely -destination 'generic/platform=iOS Simulator' build
