name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**'
      - 'Package.swift'
      - 'AI-Mixtapes.xcodeproj/**'
      - 'Docs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
        
    - name: Build documentation
      run: |
        swift package --allow-writing-to-directory ./docs \
          generate-documentation --target App \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path Encorely \
          --output-path ./docs
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
