name: Quality Gates

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-format-coverage:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools (brew)
        run: |
          brew install swiftlint swiftformat

      - name: SwiftLint
        run: swiftlint --strict

      - name: SwiftFormat Check
        run: swift format --mode lint --recursive Sources Tests

      - name: Build (debug)
        run: swift build -c debug

      - name: Test with Coverage
        run: swift test --enable-code-coverage

      - name: Export lcov
        run: |
          set -euo pipefail
          BINARY=$(find .build/debug -maxdepth 1 -type f -name '*PackageTests' -print -quit)
          if [ -z "$BINARY" ]; then echo 'Test binary not found'; exit 1; fi
          llvm-cov export -format=lcov "$BINARY" -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
          echo "Generated coverage.lcov"

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: coverage.lcov
