name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
